### ISSUE TITLE
problem python -m pip install django-counter-field

### ISSUE THREAD

**Issue by ManPython** [kajic/django-counter-field#8]
```
  Downloading https://files.pythonhosted.org/packages/d9/9e/7466aadc059a4bcc27131e23b71b66530923f8217d19907ee681127dfbfb/django-counter-field-0.3.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'E:\Python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-52pp0uoi\\django-counter-field\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-52pp0uoi\\django-counter-field\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-install-52pp0uoi\django-counter-field\pip-egg-info'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-52pp0uoi\django-counter-field\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-52pp0uoi\django-counter-field\setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by goromachine** [comment]
Same problem here when trying to upgrade the package:
I used the command:
`pip install --upgrade django-counter-field`
and the result was this:
```
Collecting django-counter-field
  Downloading django-counter-field-0.3.1.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /Volumes/Archivos/work/i4b/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lm/7tkj9gss5d561qzqm7dsvnjc0000gp/T/pip-install-9ez7z04a/django-counter-field/setup.py'"'"'; __file__='"'"'/private/var/folders/lm/7tkj9gss5d561qzqm7dsvnjc0000gp/T/pip-install-9ez7z04a/django-counter-field/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lm/7tkj9gss5d561qzqm7dsvnjc0000gp/T/pip-pip-egg-info-ohk1w8lu
         cwd: /private/var/folders/lm/7tkj9gss5d561qzqm7dsvnjc0000gp/T/pip-install-9ez7z04a/django-counter-field/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lm/7tkj9gss5d561qzqm7dsvnjc0000gp/T/pip-install-9ez7z04a/django-counter-field/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kajic** [comment]
@goromachine, @ManPython This library hasn't been maintained in a long while. Feel free to submit a pull request if you fix it.
